# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ragweaver < Formula
  desc ""
  homepage ""
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/F365-X/ragweaver/releases/download/v1.0.4/ragweaver_Darwin_x86_64.tar.gz"
      sha256 "e4ebdd05009a7f5fbfde6a1b2bd82a55389e104fba31661ea06ecd44f2e6d1a6"

      def install
        bin.install "ragweaver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/F365-X/ragweaver/releases/download/v1.0.4/ragweaver_Darwin_arm64.tar.gz"
      sha256 "9824d393c60f64fc7a9f49f0a3764fd057ac0eba6527fde80886fee9806f6aa1"

      def install
        bin.install "ragweaver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/F365-X/ragweaver/releases/download/v1.0.4/ragweaver_Linux_x86_64.tar.gz"
        sha256 "a262489af1a824a968309871d1e52040b173f3072a5ed816c2e6142981feeeaa"

        def install
          bin.install "ragweaver"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/F365-X/ragweaver/releases/download/v1.0.4/ragweaver_Linux_arm64.tar.gz"
        sha256 "eb8f4689640ceecd4b19a2407d286e33eb08ab15e0ee20ec40e1cd5f07039797"

        def install
          bin.install "ragweaver"
        end
      end
    end
  end
end
